### PR TITLE
feat: animation run once

### PR DESCRIPTION
**Pull request by hxhieu**
This allows to stop the animation when it reaches the end i.e. no looping.

PS: Sorry about the spacing differences...my IDE just stuffed up

### CODE REVIEW

**Review by LiquidityC — CHANGES_REQUESTED** [review]
Looks good. Could you just squash your commits into one before I merge? If you can't be bothered I can do it when I merge but I'm not sure if that preserves the author.

Also, please add a test or two to testsrc/AnimationTest.cpp

**Review by LiquidityC — APPROVED** [review]
Nice work. Thanks

**Comment by LiquidityC** [comment]
Just a side note. I'm not sure what editor you are using but I've reset the formatting on the entire project and added an .editorconfig and a .clang-format file. Hopefully this will prevent formatting commits for you or anyone else in the future :smile:

**Comment by hxhieu** [comment]
Oh thanks. I am using VSCode and their default formatter. At the end I had to use nano to match the tabs as VSCode just won't show yours correctly.

**Comment by LiquidityC** [comment]
VSCode should respect editorconfig. If it doesn't do it out of the box I'm certain there is a plugin for it :wink:

**Comment by hxhieu** [comment]
It sure works. Sorry if my comment was confused but I was saying that before the .editorconfig, VSCode default formatter didn't recognise the tabs well. Now things should be sorted, thanks.

**Pull request merged**
